default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: service-booking-app

test:
  <<: *default
  database: service-booking-app

production:
  <<: *default
  database: service-booking-app_production
  username: service-booking-app
  password: <%= ENV["SERVICE-BOOKING-APP_DATABASE_PASSWORD"] %>